---
openapi: 3.0.0
# swagger: "2.0"
info:
  title: Test
  description: Ejecución de programa
  termsOfService: https:localhost/terms
  contact: 
    name: ITC
    url: 'http://www.itccanarias.org'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
#host: 10.141.189.149:6757"
#basePath: "/v1"
#schemes:
#- "http"
servers:
  - url: 'http://localhost:3000'
    description: ServidorLocal
tags:
  - "ELY    

paths:
  /ELY:
    post:
      description: "Electrolyser Function"
#      operationId: "startstop"
#      consumes:
#      - "application/json"
#      - "multipart/form-data"
      parameters:
        - startstop:
          in: "formData"
          description: "Start and stop of ELY"
          name: "ELY-Off.py"
          required: true
          type: "file"

      responses:
        200:
          description: "Order"
          content:
            application/json:
              schema:
                type: "object"
        400:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                type: "string"
                example: "Error"




